# Generated by Django 4.2.4 on 2023-08-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='birth_dath',
            new_name='birth_date',
        ),
    ]
